obj-$(CONFIG_SEC_INPUT_BOOSTER)	+= input_booster_lkm.o
input_booster_lkm-$(CONFIG_SEC_INPUT_BOOSTER)	+= evdev_booster.o input_booster.o
input_booster_lkm-$(CONFIG_SEC_INPUT_BOOSTER_QC)	+= input_booster_qc.o
input_booster_lkm-$(CONFIG_SEC_INPUT_BOOSTER_SLSI)	+= input_booster_lsi.o
input_booster_lkm-$(CONFIG_SEC_INPUT_BOOSTER_MTK)	+= input_booster_mtk.o