
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o ssc_core.o
obj-$(CONFIG_LSM6DSO_FACTORY) += lsm6dso_accel.o lsm6dso_gyro.o
obj-$(CONFIG_SUPPORT_DUAL_6AXIS) += lsm6dso_sub_accel.o lsm6dso_sub_gyro.o
obj-$(CONFIG_LSM6DSL_FACTORY) += lsm6dsl_accel.o lsm6dsl_gyro.o
obj-$(CONFIG_AK09918_FACTORY) += ak09918_mag.o
obj-$(CONFIG_SUPPORT_AK0997X) += ak09970_digital_hall.o
obj-$(CONFIG_VEML3328_FACTORY) += veml3xxx_light.o
obj-$(CONFIG_VEML3328_SUB_FACTORY) += veml3xxx_sub_light.o
obj-$(CONFIG_VEML3235_FACTORY) += veml3xxx_light.o
obj-$(CONFIG_VEML3235_SUB_FACTORY) += veml3xxx_sub_light.o
obj-$(CONFIG_LPS22HH_FACTORY) += lps22hh_pressure.o
obj-$(CONFIG_TMD49XX_FACTORY) += tmd49xx_light.o tmd49xx_prox.o
obj-$(CONFIG_STK3A9X_FACTORY) += stk3a9x_light.o stk3a9x_prox.o
obj-$(CONFIG_TCS3701_FACTORY) += tcs3701_light.o
obj-$(CONFIG_STK3331_FACTORY) += stk3331_prox.o
